[pytest]
minversion = 7.0
addopts = -ra -q --strict-markers --ignore=scratch
testpaths =
    .
filterwarnings =
    ignore::DeprecationWarning
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    regression: regression tests
    asyncio: asyncio tests
    issue958: issue 958 tests
