[pytest]
minversion = 7.0
addopts = -ra -q --strict-markers
testpaths =
    .
filterwarnings =
    ignore::DeprecationWarning
markers =
    slow: mark test as slow
    asyncio: mark test as asyncio
    regression: mark test as regression
    issue958: issue 958
