import os

base_dir = r"F:\ECSoC'26 Contributions\eco-buddy-ai"
test_file = os.path.join(base_dir, "test_environmental_benchmarks_integration.py")

with open(test_file, "a") as f:
    f.write("""
    def test_advanced_stats_and_recommendation_synergy(self):
        \"\"\"
        Test that recommendations correctly map to normalized scores and Z-scores.
        This tests the synergy between the advanced mathematical models and the 
        final user-facing strings generated by the engine.
        \"\"\"
        latest = self.history_analyzer.get_user_history(user_id=1)[-1]
        res = self.engine.compare_assessment(latest, 'target')
        
        # Test Z-score correlation
        z = DataNormalizer.z_score_normalize(
            latest.footprint, 
            res.categories['footprint'].reference_mean, 
            self.engine.profiles['target'].footprint_stat.std_dev
        )
        
        # The user's footprint is 5000, which is extremely high for 'target' (avg ~2000)
        self.assertTrue(z > 1.5)
        
        # Since it's a terrible score relative to 'target', recommendations should be critical
        recs = self.recommendation_engine.generate_recommendations(res.categories)
        has_critical = any("CRITICAL" in r for r in recs)
        self.assertTrue(has_critical, f"Expected CRITICAL recommendations for Z-score {z}, got {recs}")
        
        # Conversely, if we test against US, Z-score should be good
        res_us = self.engine.compare_assessment(latest, 'us')
        z_us = DataNormalizer.z_score_normalize(
            latest.footprint, 
            res_us.categories['footprint'].reference_mean, 
            self.engine.profiles['us'].footprint_stat.std_dev
        )
        self.assertTrue(z_us < -0.5) # better than average
        recs_us = self.recommendation_engine.generate_recommendations(res_us.categories)
        self.assertFalse(any("CRITICAL" in r for r in recs_us))
""")
